### PR TITLE
Notifications toggle

### PR DESCRIPTION
**Pull request by Rjbeckwith55**
I think I added notification toggle everywhere important. Let me know if I am missing something.

### CODE REVIEW

**Comment by jeffreyj100** [comment]
Have we agreed on storing user preferences/settings on the database? Why not locally on the device?

**Comment by Rjbeckwith55** [comment]
It seems pretty easy to add to the account and it makes sense to link that to the account imo. You would want the notifications settings to be saved if you uninstall the app and stuff like that. You don't want to set them each time.

**Comment by jeffreyj100** [comment]
Ok, that makes sense. What other user settings do we plan to have by the end of last iteration?

**Comment by Rjbeckwith55** [comment]
As of right now I can't think of others. We might not end up with any because there are other features that are more important I think.

**Comment by jeffreyj100** [comment]
Ok, then its good to merge.

**Pull request merged**
