### PR TITLE
Notifications toggle

### PR DESCRIPTION
**Pull request by Rjbeckwith55**

### CODE REVIEW

**Comment by Rjbeckwith55** [comment]
Pull Request for getting the current user data.

**Comment by jeffreyj100** [comment]
Can you also add test case for non-existing user for complete test coverage?

**Comment by Rjbeckwith55** [comment]
@jeffreyj100 Good point. I have added the other test in. We might be able to add failure tests to some of the others too I don't think they all have them.

**Comment by jeffreyj100** [comment]
Yes, lets aim for as much test coverage as possible (90%+) even on frontend also.

**Comment by jeffreyj100** [comment]
Looks fine, good to merge.

**Pull request merged**
